name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            playground/package-lock.json
      - name: Write playground .env
        run: |
          printf '%s' "${{ secrets.PLAYGROUND_ENV_BASE64 }}" | base64 -d > playground/.env
      - name: Install root deps
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Verify plugin
        run: npm run verify
      - name: Pack plugin into playground .yalc
        run: |
          TARBALL=$(npm pack --silent)
          mkdir -p playground/.yalc/strapi-plugin-checkbox-list
          tar -xzf "$TARBALL" -C playground/.yalc/strapi-plugin-checkbox-list --strip-components=1
      - name: Install playground deps
        working-directory: playground
        run: npm install
      - name: Build playground
        working-directory: playground
        run: npm run build
      - name: Integration tests
        working-directory: playground
        run: npm run test:integration
