name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            playground/package-lock.json
      - name: Install root deps
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Verify plugin
        run: npm run verify
      - name: Pack plugin into playground .yalc
        run: |
          TARBALL=$(npm pack --silent)
          mkdir -p playground/.yalc/strapi-plugin-checkbox-list
          tar -xzf "$TARBALL" -C playground/.yalc/strapi-plugin-checkbox-list --strip-components=1
      - name: Install playground deps
        run: npm ci --prefix playground
      - name: Build playground
        run: npm run build --prefix playground
      - name: Integration tests (Jest + Supertest)
        run: npm run test:integration --prefix playground

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: test
    env:
      STRAPI_ADMIN_EMAIL: admin@example.com
      STRAPI_ADMIN_PASSWORD: Admin12345
      STRAPI_ADMIN_FIRSTNAME: Admin
      STRAPI_ADMIN_LASTNAME: User
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            playground/package-lock.json
      - name: Install root deps
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Pack plugin into playground .yalc
        run: |
          TARBALL=$(npm pack --silent)
          mkdir -p playground/.yalc/strapi-plugin-checkbox-list
          tar -xzf "$TARBALL" -C playground/.yalc/strapi-plugin-checkbox-list --strip-components=1
      - name: Install playground deps
        run: npm ci --prefix playground
      - name: Create admin user
        run: |
          cd playground
          npx strapi admin:create-user \
            --email "$STRAPI_ADMIN_EMAIL" \
            --password "$STRAPI_ADMIN_PASSWORD" \
            --firstname "$STRAPI_ADMIN_FIRSTNAME" \
            --lastname "$STRAPI_ADMIN_LASTNAME"
      - name: Start Strapi
        run: |
          npm run develop --prefix playground -- --host 0.0.0.0 --port 1337 &
          echo $! > /tmp/strapi.pid
          until curl -sSf http://127.0.0.1:1337/admin >/dev/null; do sleep 2; done
      - name: E2E tests (Playwright/Cypress)
        run: npm run e2e --prefix playground
      - name: Stop Strapi
        if: always()
        run: |
          if [ -f /tmp/strapi.pid ]; then
            kill "$(cat /tmp/strapi.pid)" || true
          fi
